/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Cliente;
import model.bean.Cliente;
import model.dao.ClienteDao;

/**
 *
 * @author viniciusdias
 */
public class ClientesView extends javax.swing.JFrame {
    String modoCli;
    /**
     * Creates new form Principal
     */
    public ClientesView() {
        initComponents();
        setLocationRelativeTo(null);
        modoCli = "Navegar";
        ManipulaInterfaceCli();
        
        DefaultTableModel modelo = (DefaultTableModel) tbl_cli_clis.getModel();
        tbl_cli_clis.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }
    public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) tbl_cli_clis.getModel();
        modelo.setNumRows(0);
        ClienteDao cdao = new ClienteDao();
        
        for(Cliente c: cdao.read()){
            
            modelo.addRow(new Object[]{
                
                c.getCpf(),
                c.getNome(),
                c.getEmail()
            });
        }
        
    }    
    
    public void ManipulaInterfaceCli(){
        switch(modoCli){
            case "Navegar":
                btn_cli_salvar.setEnabled(false);
                btn_cli_voltar.setEnabled(true);
                c_cli_nome.setEnabled(false);
                c_cli_cpf.setEnabled(false);
                c_cli_email.setEnabled(false);
                btn_cli_novo.setEnabled(true);
                btn_cli_editar.setEnabled(false);
                btn_cli_excluir.setEnabled(true);
                break;
            
            case "Novo":
                btn_cli_salvar.setEnabled(true);
                btn_cli_voltar.setEnabled(true);
                c_cli_nome.setEnabled(true);
                c_cli_cpf.setEnabled(true);
                c_cli_email.setEnabled(true);
                btn_cli_novo.setEnabled(false);
                btn_cli_editar.setEnabled(false);
                btn_cli_excluir.setEnabled(false);
                break;
                
            case "Editar":
                btn_cli_salvar.setEnabled(true);
                btn_cli_voltar.setEnabled(true);
                c_cli_nome.setEnabled(true);
                c_cli_cpf.setEnabled(true);
                c_cli_email.setEnabled(true);
                btn_cli_novo.setEnabled(true);
                btn_cli_editar.setEnabled(false);
                btn_cli_excluir.setEnabled(false);
                break;
                
            case "Excluir":
                btn_cli_salvar.setEnabled(false);
                btn_cli_voltar.setEnabled(false);
                c_cli_nome.setEnabled(false);
                c_cli_cpf.setEnabled(false);
                c_cli_email.setEnabled(false);
                btn_cli_novo.setEnabled(true);
                btn_cli_editar.setEnabled(false);
                btn_cli_excluir.setEnabled(false);
                break;
                
            case "Selecao":
                btn_cli_salvar.setEnabled(false);
                btn_cli_voltar.setEnabled(false);
                c_cli_nome.setEnabled(false);
                c_cli_cpf.setEnabled(false);
                c_cli_email.setEnabled(false);
                btn_cli_novo.setEnabled(true);
                btn_cli_editar.setEnabled(true);
                btn_cli_excluir.setEnabled(true);
                break;
            default: System.out.println("Modo inválido");
        }
    }
    private void limpaTextoCli () {
        c_cli_nome.setText("");
        c_cli_cpf.setText("");
        c_cli_email.setText("");
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_cli_editar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_cli_clis = new javax.swing.JTable();
        btn_cli_excluir = new javax.swing.JButton();
        btn_cli_salvar = new javax.swing.JButton();
        btn_cli_voltar = new javax.swing.JButton();
        btn_cli_novo = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        c_cli_cpf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        c_cli_nome = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        c_cli_email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Adicionar Cliente"));

        btn_cli_editar.setText("Atualizar");
        btn_cli_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cli_editarActionPerformed(evt);
            }
        });

        tbl_cli_clis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cpf", "Nome", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_cli_clis);

        btn_cli_excluir.setText("Excluir");
        btn_cli_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cli_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(btn_cli_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cli_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cli_excluir)
                    .addComponent(btn_cli_editar))
                .addContainerGap())
        );

        btn_cli_salvar.setText("Salvar");
        btn_cli_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cli_salvarActionPerformed(evt);
            }
        });

        btn_cli_voltar.setText("Voltar");
        btn_cli_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cli_voltarActionPerformed(evt);
            }
        });

        btn_cli_novo.setText("Novo");
        btn_cli_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cli_novoActionPerformed(evt);
            }
        });

        jLabel15.setText("Cpf:");

        jLabel16.setText("Nome:");

        jLabel17.setText("Email:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btn_cli_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addComponent(btn_cli_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(c_cli_nome)
                            .addComponent(c_cli_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_cli_email)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btn_cli_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_cli_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_cli_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(c_cli_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cli_salvar)
                    .addComponent(btn_cli_novo))
                .addGap(18, 18, 18)
                .addComponent(btn_cli_voltar)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cli_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cli_salvarActionPerformed
        Cliente c = new Cliente();
        ClienteDao dao = new ClienteDao();
        c.setNome(c_cli_nome.getText());
        c.setCpf(Long.parseLong(c_cli_cpf.getText()));
        c.setEmail(c_cli_email.getText());
        
        dao.create(c);

        modoCli = "Navegar";
        ManipulaInterfaceCli();
        limpaTextoCli();
        readJTable();
    }//GEN-LAST:event_btn_cli_salvarActionPerformed

    private void btn_cli_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cli_voltarActionPerformed
        new administradorView().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_cli_voltarActionPerformed

    private void btn_cli_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cli_novoActionPerformed
        modoCli = "Novo";
        ManipulaInterfaceCli();
    }//GEN-LAST:event_btn_cli_novoActionPerformed

    private void btn_cli_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cli_editarActionPerformed
        if(tbl_cli_clis.getSelectedRow() != -1) {

        }

        modoCli = "Editar";
        ManipulaInterfaceCli();
    }//GEN-LAST:event_btn_cli_editarActionPerformed

    private void btn_cli_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cli_excluirActionPerformed
        if(tbl_cli_clis.getSelectedRow() != -1) {

            Cliente c = new Cliente();
            ClienteDao dao = new ClienteDao();

            c.setNome((String) tbl_cli_clis.getValueAt(tbl_cli_clis.getSelectedRow(), 1));

            dao.delete(c);

            readJTable();

        }

        modoCli = "Navegar";
        ManipulaInterfaceCli();
    }//GEN-LAST:event_btn_cli_excluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cli_editar;
    private javax.swing.JButton btn_cli_excluir;
    private javax.swing.JButton btn_cli_novo;
    private javax.swing.JButton btn_cli_salvar;
    private javax.swing.JButton btn_cli_voltar;
    private javax.swing.JTextField c_cli_cpf;
    private javax.swing.JTextField c_cli_email;
    private javax.swing.JTextField c_cli_nome;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_cli_clis;
    // End of variables declaration//GEN-END:variables
}
