/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteControl;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author viniciusdias
 */
public class ClientesView extends javax.swing.JFrame {
    String modoCli;
    /**
     * Creates new form Principal
     */
    public ClientesView() {
        initComponents();
        setLocationRelativeTo(null);
        modoCli = "Navegar";
        ManipulaInterfaceCli();
        
        DefaultTableModel modelo = (DefaultTableModel) tbl_cli_clis.getModel();
        tbl_cli_clis.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }
    public void readJTable() {
        
        ClienteControl.getCliente((DefaultTableModel) tbl_cli_clis.getModel());
        
    }    
    
    public void ManipulaInterfaceCli(){
        switch(modoCli){
            case "Navegar":
                btn_cli_salvar.setEnabled(false);
                btn_cli_voltar.setEnabled(true);
                c_cli_nome.setEnabled(false);
                c_cli_cpf.setEnabled(false);
                c_cli_email.setEnabled(false);
                btn_cli_novo.setEnabled(true);
                btn_cli_atualizar.setEnabled(false);
                btn_cli_excluir.setEnabled(true);
                break;
            
            case "Novo":
                btn_cli_salvar.setEnabled(true);
                btn_cli_voltar.setEnabled(true);
                c_cli_nome.setEnabled(true);
                c_cli_cpf.setEnabled(true);
                c_cli_email.setEnabled(true);
                btn_cli_novo.setEnabled(false);
                btn_cli_atualizar.setEnabled(false);
                btn_cli_excluir.setEnabled(false);
                break;
                
            case "Editar":
                btn_cli_salvar.setEnabled(true);
                btn_cli_voltar.setEnabled(true);
                c_cli_nome.setEnabled(true);
                c_cli_cpf.setEnabled(true);
                c_cli_email.setEnabled(true);
                btn_cli_novo.setEnabled(true);
                btn_cli_atualizar.setEnabled(true);
                btn_cli_excluir.setEnabled(true);
                break;
                
            case "Excluir":
                btn_cli_salvar.setEnabled(false);
                btn_cli_voltar.setEnabled(false);
                c_cli_nome.setEnabled(false);
                c_cli_cpf.setEnabled(false);
                c_cli_email.setEnabled(false);
                btn_cli_novo.setEnabled(true);
                btn_cli_atualizar.setEnabled(false);
                btn_cli_excluir.setEnabled(false);
                break;
                
            case "Selecao":
                btn_cli_salvar.setEnabled(false);
                btn_cli_voltar.setEnabled(false);
                c_cli_nome.setEnabled(false);
                c_cli_cpf.setEnabled(false);
                c_cli_email.setEnabled(false);
                btn_cli_novo.setEnabled(true);
                btn_cli_atualizar.setEnabled(true);
                btn_cli_excluir.setEnabled(true);
                break;
            default: System.out.println("Modo inválido");
        }
    }
    private void limpaTextoCli () {
        c_cli_nome.setText("");
        c_cli_cpf.setText("");
        c_cli_email.setText("");
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_cli_salvar = new javax.swing.JButton();
        btn_cli_voltar = new javax.swing.JButton();
        btn_cli_novo = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        c_cli_cpf = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        c_cli_nome = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        c_cli_email = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_cli_clis = new javax.swing.JTable();
        btn_cli_atualizar = new javax.swing.JButton();
        btn_cli_excluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Adicionar Cliente"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_cli_salvar.setText("Salvar");
        btn_cli_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cli_salvarActionPerformed(evt);
            }
        });

        btn_cli_voltar.setText("Voltar");
        btn_cli_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cli_voltarActionPerformed(evt);
            }
        });

        btn_cli_novo.setText("Novo");
        btn_cli_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cli_novoActionPerformed(evt);
            }
        });

        jLabel15.setText("Cpf:");

        c_cli_cpf.setText("09058111946666");

        jLabel16.setText("Nome:");

        c_cli_nome.setText("Vinicius Monteiro Dias");

        jLabel17.setText("Email:");

        c_cli_email.setText("vinicius-mdias@hotmail.com");

        tbl_cli_clis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cpf", "Nome", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_cli_clis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cli_clisMouseClicked(evt);
            }
        });
        tbl_cli_clis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_cli_clisKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_cli_clis);

        btn_cli_atualizar.setText("Atualizar");
        btn_cli_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cli_atualizarActionPerformed(evt);
            }
        });

        btn_cli_excluir.setText("Excluir");
        btn_cli_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cli_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btn_cli_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(btn_cli_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(102, 102, 102)
                                .addComponent(jLabel16)
                                .addGap(107, 107, 107)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_cli_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cli_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(c_cli_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(c_cli_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btn_cli_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btn_cli_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_cli_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_cli_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c_cli_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cli_novo)
                            .addComponent(btn_cli_salvar)
                            .addComponent(btn_cli_voltar))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cli_excluir)
                            .addComponent(btn_cli_atualizar))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cli_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cli_salvarActionPerformed
        ClienteControl.salvarCliente(c_cli_cpf.getText(), c_cli_nome.getText(), c_cli_cpf.getText());
        
        modoCli = "Navegar";
        ManipulaInterfaceCli();
        limpaTextoCli();
        readJTable();
    }//GEN-LAST:event_btn_cli_salvarActionPerformed

    private void btn_cli_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cli_voltarActionPerformed
        new administradorView().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_cli_voltarActionPerformed

    private void btn_cli_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cli_novoActionPerformed
        modoCli = "Novo";
        ManipulaInterfaceCli();
    }//GEN-LAST:event_btn_cli_novoActionPerformed

    private void btn_cli_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cli_atualizarActionPerformed
        if(tbl_cli_clis.getSelectedRow() != -1) {
 
            ClienteControl.updateCliente(c_cli_cpf.getText(), c_cli_nome.getText(), c_cli_cpf.getText());
            modoCli = "Navegar";
            ManipulaInterfaceCli();
            limpaTextoCli();
            readJTable();         
        }

        modoCli = "Editar";
        ManipulaInterfaceCli();
    }//GEN-LAST:event_btn_cli_atualizarActionPerformed

    private void btn_cli_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cli_excluirActionPerformed
        if(tbl_cli_clis.getSelectedRow() != -1) {
            ClienteControl.deletarCliente(tbl_cli_clis.getValueAt(tbl_cli_clis.getSelectedRow(), 1).toString());
            readJTable();
        }

        modoCli = "Navegar";
        ManipulaInterfaceCli();
    }//GEN-LAST:event_btn_cli_excluirActionPerformed

    private void tbl_cli_clisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_cli_clisKeyReleased
        if(tbl_cli_clis.getSelectedRow() != -1) {

            
            c_cli_cpf.setText(tbl_cli_clis.getValueAt(tbl_cli_clis.getSelectedRow(), 0).toString());
            c_cli_nome.setText(tbl_cli_clis.getValueAt(tbl_cli_clis.getSelectedRow(), 1).toString());
            c_cli_email.setText(tbl_cli_clis.getValueAt(tbl_cli_clis.getSelectedRow(), 2).toString());

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_cli_clisKeyReleased

    private void tbl_cli_clisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cli_clisMouseClicked
        if(tbl_cli_clis.getSelectedRow() != -1) {

            
            c_cli_cpf.setText(tbl_cli_clis.getValueAt(tbl_cli_clis.getSelectedRow(), 0).toString());
            c_cli_nome.setText(tbl_cli_clis.getValueAt(tbl_cli_clis.getSelectedRow(), 1).toString());
            c_cli_email.setText(tbl_cli_clis.getValueAt(tbl_cli_clis.getSelectedRow(), 2).toString());

        }
        modoCli = "Editar";
        ManipulaInterfaceCli();        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_cli_clisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientesView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cli_atualizar;
    private javax.swing.JButton btn_cli_excluir;
    private javax.swing.JButton btn_cli_novo;
    private javax.swing.JButton btn_cli_salvar;
    private javax.swing.JButton btn_cli_voltar;
    private javax.swing.JTextField c_cli_cpf;
    private javax.swing.JTextField c_cli_email;
    private javax.swing.JTextField c_cli_nome;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_cli_clis;
    // End of variables declaration//GEN-END:variables
}
