/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Administrador;
import model.bean.Cliente;
import model.bean.Produto;
import model.dao.AdministradorDao;
import model.dao.ProdutoDao;

/**
 *
 * @author viniciusdias
 */
public class ProdutosView extends javax.swing.JFrame {
    String modoProd;
    /**
     * Creates new form Principal
     */
    public ProdutosView() {
        initComponents();
        setLocationRelativeTo(null);
        modoProd = "Navegar";
        ManipulaInterfaceProd();
        
        DefaultTableModel modelo = (DefaultTableModel) tbl_prod_prods3.getModel();
        tbl_prod_prods3.setRowSorter(new TableRowSorter(modelo));
        readJTable();
    }
    
    
        public void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) tbl_prod_prods3.getModel();
        modelo.setNumRows(0);
        ProdutoDao pdao = new ProdutoDao();
        
        for(Produto p: pdao.read()){
            
            modelo.addRow(new Object[]{
                
                p.getQuantidade(),
                p.getNome()
                
                
            });
            
        }
        
    }
    
    public void ManipulaInterfaceProd(){
        switch(modoProd){
            case "Navegar":
                btn_prod_salvar.setEnabled(false);
                btn_prod_voltar.setEnabled(true);
                c_prod_qtd.setEnabled(false);
                c_prod_nome.setEnabled(false);
                btn_prod_novo.setEnabled(true);
                btn_prod_editar3.setEnabled(false);
                btn_prod_excluir3.setEnabled(true);
                break;
            
            case "Novo":
                btn_prod_salvar.setEnabled(true);
                btn_prod_voltar.setEnabled(true);
                c_prod_qtd.setEnabled(true);
                c_prod_nome.setEnabled(true);
                btn_prod_novo.setEnabled(false);
                btn_prod_editar3.setEnabled(false);
                btn_prod_excluir3.setEnabled(false);
                break;
                
            case "Editar":
                btn_prod_salvar.setEnabled(true);
                btn_prod_voltar.setEnabled(true);
                c_prod_qtd.setEnabled(true);
                c_prod_nome.setEnabled(true);
                btn_prod_novo.setEnabled(true);
                btn_prod_editar3.setEnabled(false);
                btn_prod_excluir3.setEnabled(false);
                break;
                
            case "Excluir":
                btn_prod_salvar.setEnabled(false);
                btn_prod_voltar.setEnabled(false);
                c_prod_qtd.setEnabled(false);
                c_prod_nome.setEnabled(false);
                btn_prod_novo.setEnabled(true);
                btn_prod_editar3.setEnabled(false);
                btn_prod_excluir3.setEnabled(false);
                break;
                
            case "Selecao":
                btn_prod_salvar.setEnabled(false);
                btn_prod_voltar.setEnabled(false);
                c_prod_qtd.setEnabled(false);
                c_prod_nome.setEnabled(false);
                btn_prod_novo.setEnabled(true);
                btn_prod_editar3.setEnabled(true);
                btn_prod_excluir3.setEnabled(true);
                break;
            default: System.out.println("Modo inválido");
        }
    }
    private void limpaTextoProd () {
        c_prod_qtd.setText("");
        c_prod_nome.setText("");
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        c_prod_qtd = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        c_prod_nome = new javax.swing.JTextField();
        btn_prod_salvar = new javax.swing.JButton();
        btn_prod_voltar = new javax.swing.JButton();
        btn_prod_novo = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_prod_editar3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_prod_prods3 = new javax.swing.JTable();
        btn_prod_excluir3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Produto"));

        jLabel13.setText("Quantidade:");

        jLabel14.setText("Nome:");

        btn_prod_salvar.setText("Salvar");
        btn_prod_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_salvarActionPerformed(evt);
            }
        });

        btn_prod_voltar.setText("Voltar");
        btn_prod_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_voltarActionPerformed(evt);
            }
        });

        btn_prod_novo.setText("Novo");
        btn_prod_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_novoActionPerformed(evt);
            }
        });

        btn_prod_editar3.setText("Editar");
        btn_prod_editar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_editar3ActionPerformed(evt);
            }
        });

        tbl_prod_prods3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantidade", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tbl_prod_prods3);

        btn_prod_excluir3.setText("Excluir");
        btn_prod_excluir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prod_excluir3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btn_prod_editar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_prod_excluir3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_prod_excluir3)
                    .addComponent(btn_prod_editar3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(btn_prod_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_prod_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(c_prod_nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(c_prod_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btn_prod_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_prod_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_prod_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_prod_salvar)
                    .addComponent(btn_prod_novo))
                .addGap(18, 18, 18)
                .addComponent(btn_prod_voltar)
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_prod_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_salvarActionPerformed
        Produto p = new Produto();
        ProdutoDao dao = new ProdutoDao();
        p.setNome(c_prod_nome.getText());
        p.setQuantidade(Integer.parseInt(c_prod_qtd.getText()));
        
        dao.create(p);

        modoProd = "Navegar";
        ManipulaInterfaceProd();
        limpaTextoProd();
        
        readJTable();
    }//GEN-LAST:event_btn_prod_salvarActionPerformed

    private void btn_prod_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_voltarActionPerformed
        new administradorView().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btn_prod_voltarActionPerformed

    private void btn_prod_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_novoActionPerformed
        modoProd = "Novo";
        ManipulaInterfaceProd();
    }//GEN-LAST:event_btn_prod_novoActionPerformed

    private void btn_prod_editar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_editar3ActionPerformed
        modoProd = "Editar";
        ManipulaInterfaceProd();
    }//GEN-LAST:event_btn_prod_editar3ActionPerformed

    private void btn_prod_excluir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prod_excluir3ActionPerformed
        if(tbl_prod_prods3.getSelectedRow() != -1) {

            Produto p = new Produto();
            ProdutoDao dao = new ProdutoDao();

            p.setNome((String) tbl_prod_prods3.getValueAt(tbl_prod_prods3.getSelectedRow(), 1));

            dao.delete(p);

            readJTable();

        }
        modoProd = "Navegar";
        ManipulaInterfaceProd();
    }//GEN-LAST:event_btn_prod_excluir3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_prod_editar3;
    private javax.swing.JButton btn_prod_excluir3;
    private javax.swing.JButton btn_prod_novo;
    private javax.swing.JButton btn_prod_salvar;
    private javax.swing.JButton btn_prod_voltar;
    private javax.swing.JTextField c_prod_nome;
    private javax.swing.JTextField c_prod_qtd;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tbl_prod_prods3;
    // End of variables declaration//GEN-END:variables
}
